//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/_Main/_Scripts/IO/InputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @InputActions: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @InputActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""InputActions"",
    ""maps"": [
        {
            ""name"": ""VN"",
            ""id"": ""097095ec-854e-408d-99d9-8340c1d27a42"",
            ""actions"": [
                {
                    ""name"": ""ForwardAction"",
                    ""type"": ""Button"",
                    ""id"": ""f4c70e3d-c7c9-4575-b403-2135b91d8c9c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""AutoAction"",
                    ""type"": ""Button"",
                    ""id"": ""1074b929-f3d5-4707-8a5f-2dd37a9b7005"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SkipAction"",
                    ""type"": ""Button"",
                    ""id"": ""a21e172e-7e8a-4f26-a487-ef588f11ac6e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SkipHoldAction"",
                    ""type"": ""Button"",
                    ""id"": ""761eeb8b-f975-4309-a817-158bc9d5a34e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""DialogueBackAction"",
                    ""type"": ""Button"",
                    ""id"": ""137331eb-2fa5-441f-a2b7-fd2f70429606"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LogAction"",
                    ""type"": ""Button"",
                    ""id"": ""f01727a9-ed9c-488e-805b-e826ee8467b2"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ScrollAction"",
                    ""type"": ""Value"",
                    ""id"": ""ed94ecc6-4c59-4e89-9ab3-77525863e60f"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""MenuNavigationAction"",
                    ""type"": ""Button"",
                    ""id"": ""c84e0024-fce7-4f24-8a0f-d365992aeac6"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ConfirmAction"",
                    ""type"": ""Button"",
                    ""id"": ""45d9eaeb-6494-4b89-94a0-d80642517531"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""3e566561-99b2-4b39-8da8-6ff0251f8527"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ForwardAction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""dc00ba4f-d08e-46e7-bd72-fad20993ed8f"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ForwardAction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8f75381d-b44c-4d25-a018-09c191bdc11d"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AutoAction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""06c7aecb-feb6-46cf-a71a-90fbc0dde8bd"",
                    ""path"": ""<Keyboard>/ctrl"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SkipAction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""49480f45-3fd7-4395-812c-528558e6c5d9"",
                    ""path"": ""<Keyboard>/ctrl"",
                    ""interactions"": ""Hold(duration=0.5,pressPoint=0.5)"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SkipHoldAction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f19a7ea0-20e5-4fc5-878e-81747b0ee5f9"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DialogueBackAction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5b0c15b4-5a59-4634-a19a-bc072dfc555e"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LogAction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e35fa224-557d-4490-8ad3-74bd618411ec"",
                    ""path"": ""<Mouse>/scroll"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ScrollAction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5c645f04-db6c-4793-9c1e-a47234f61fe7"",
                    ""path"": ""<Touchscreen>/primaryTouch/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ScrollAction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e74e03c5-f896-4864-9835-7db76c15c082"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MenuNavigationAction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ed71f183-f2ed-48a0-a840-63cd54d8525c"",
                    ""path"": ""<Keyboard>/enter"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ConfirmAction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // VN
        m_VN = asset.FindActionMap("VN", throwIfNotFound: true);
        m_VN_ForwardAction = m_VN.FindAction("ForwardAction", throwIfNotFound: true);
        m_VN_AutoAction = m_VN.FindAction("AutoAction", throwIfNotFound: true);
        m_VN_SkipAction = m_VN.FindAction("SkipAction", throwIfNotFound: true);
        m_VN_SkipHoldAction = m_VN.FindAction("SkipHoldAction", throwIfNotFound: true);
        m_VN_DialogueBackAction = m_VN.FindAction("DialogueBackAction", throwIfNotFound: true);
        m_VN_LogAction = m_VN.FindAction("LogAction", throwIfNotFound: true);
        m_VN_ScrollAction = m_VN.FindAction("ScrollAction", throwIfNotFound: true);
        m_VN_MenuNavigationAction = m_VN.FindAction("MenuNavigationAction", throwIfNotFound: true);
        m_VN_ConfirmAction = m_VN.FindAction("ConfirmAction", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // VN
    private readonly InputActionMap m_VN;
    private List<IVNActions> m_VNActionsCallbackInterfaces = new List<IVNActions>();
    private readonly InputAction m_VN_ForwardAction;
    private readonly InputAction m_VN_AutoAction;
    private readonly InputAction m_VN_SkipAction;
    private readonly InputAction m_VN_SkipHoldAction;
    private readonly InputAction m_VN_DialogueBackAction;
    private readonly InputAction m_VN_LogAction;
    private readonly InputAction m_VN_ScrollAction;
    private readonly InputAction m_VN_MenuNavigationAction;
    private readonly InputAction m_VN_ConfirmAction;
    public struct VNActions
    {
        private @InputActions m_Wrapper;
        public VNActions(@InputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @ForwardAction => m_Wrapper.m_VN_ForwardAction;
        public InputAction @AutoAction => m_Wrapper.m_VN_AutoAction;
        public InputAction @SkipAction => m_Wrapper.m_VN_SkipAction;
        public InputAction @SkipHoldAction => m_Wrapper.m_VN_SkipHoldAction;
        public InputAction @DialogueBackAction => m_Wrapper.m_VN_DialogueBackAction;
        public InputAction @LogAction => m_Wrapper.m_VN_LogAction;
        public InputAction @ScrollAction => m_Wrapper.m_VN_ScrollAction;
        public InputAction @MenuNavigationAction => m_Wrapper.m_VN_MenuNavigationAction;
        public InputAction @ConfirmAction => m_Wrapper.m_VN_ConfirmAction;
        public InputActionMap Get() { return m_Wrapper.m_VN; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(VNActions set) { return set.Get(); }
        public void AddCallbacks(IVNActions instance)
        {
            if (instance == null || m_Wrapper.m_VNActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_VNActionsCallbackInterfaces.Add(instance);
            @ForwardAction.started += instance.OnForwardAction;
            @ForwardAction.performed += instance.OnForwardAction;
            @ForwardAction.canceled += instance.OnForwardAction;
            @AutoAction.started += instance.OnAutoAction;
            @AutoAction.performed += instance.OnAutoAction;
            @AutoAction.canceled += instance.OnAutoAction;
            @SkipAction.started += instance.OnSkipAction;
            @SkipAction.performed += instance.OnSkipAction;
            @SkipAction.canceled += instance.OnSkipAction;
            @SkipHoldAction.started += instance.OnSkipHoldAction;
            @SkipHoldAction.performed += instance.OnSkipHoldAction;
            @SkipHoldAction.canceled += instance.OnSkipHoldAction;
            @DialogueBackAction.started += instance.OnDialogueBackAction;
            @DialogueBackAction.performed += instance.OnDialogueBackAction;
            @DialogueBackAction.canceled += instance.OnDialogueBackAction;
            @LogAction.started += instance.OnLogAction;
            @LogAction.performed += instance.OnLogAction;
            @LogAction.canceled += instance.OnLogAction;
            @ScrollAction.started += instance.OnScrollAction;
            @ScrollAction.performed += instance.OnScrollAction;
            @ScrollAction.canceled += instance.OnScrollAction;
            @MenuNavigationAction.started += instance.OnMenuNavigationAction;
            @MenuNavigationAction.performed += instance.OnMenuNavigationAction;
            @MenuNavigationAction.canceled += instance.OnMenuNavigationAction;
            @ConfirmAction.started += instance.OnConfirmAction;
            @ConfirmAction.performed += instance.OnConfirmAction;
            @ConfirmAction.canceled += instance.OnConfirmAction;
        }

        private void UnregisterCallbacks(IVNActions instance)
        {
            @ForwardAction.started -= instance.OnForwardAction;
            @ForwardAction.performed -= instance.OnForwardAction;
            @ForwardAction.canceled -= instance.OnForwardAction;
            @AutoAction.started -= instance.OnAutoAction;
            @AutoAction.performed -= instance.OnAutoAction;
            @AutoAction.canceled -= instance.OnAutoAction;
            @SkipAction.started -= instance.OnSkipAction;
            @SkipAction.performed -= instance.OnSkipAction;
            @SkipAction.canceled -= instance.OnSkipAction;
            @SkipHoldAction.started -= instance.OnSkipHoldAction;
            @SkipHoldAction.performed -= instance.OnSkipHoldAction;
            @SkipHoldAction.canceled -= instance.OnSkipHoldAction;
            @DialogueBackAction.started -= instance.OnDialogueBackAction;
            @DialogueBackAction.performed -= instance.OnDialogueBackAction;
            @DialogueBackAction.canceled -= instance.OnDialogueBackAction;
            @LogAction.started -= instance.OnLogAction;
            @LogAction.performed -= instance.OnLogAction;
            @LogAction.canceled -= instance.OnLogAction;
            @ScrollAction.started -= instance.OnScrollAction;
            @ScrollAction.performed -= instance.OnScrollAction;
            @ScrollAction.canceled -= instance.OnScrollAction;
            @MenuNavigationAction.started -= instance.OnMenuNavigationAction;
            @MenuNavigationAction.performed -= instance.OnMenuNavigationAction;
            @MenuNavigationAction.canceled -= instance.OnMenuNavigationAction;
            @ConfirmAction.started -= instance.OnConfirmAction;
            @ConfirmAction.performed -= instance.OnConfirmAction;
            @ConfirmAction.canceled -= instance.OnConfirmAction;
        }

        public void RemoveCallbacks(IVNActions instance)
        {
            if (m_Wrapper.m_VNActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IVNActions instance)
        {
            foreach (var item in m_Wrapper.m_VNActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_VNActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public VNActions @VN => new VNActions(this);
    public interface IVNActions
    {
        void OnForwardAction(InputAction.CallbackContext context);
        void OnAutoAction(InputAction.CallbackContext context);
        void OnSkipAction(InputAction.CallbackContext context);
        void OnSkipHoldAction(InputAction.CallbackContext context);
        void OnDialogueBackAction(InputAction.CallbackContext context);
        void OnLogAction(InputAction.CallbackContext context);
        void OnScrollAction(InputAction.CallbackContext context);
        void OnMenuNavigationAction(InputAction.CallbackContext context);
        void OnConfirmAction(InputAction.CallbackContext context);
    }
}
